### ISSUE TITLE
The problem with self.walk_target_dist_xyz in robot_locomotors.py

### ISSUE THREAD

**Issue by Berk035** [StanfordVL/GibsonEnv#103]
Hello everyone,

I noticed an error in robot_locomotors.py line 162. The code:
` self.walk_target_dist_xyz = np.linalg.norm(
            [self.target_pos[2] - self.body_xyz[2], self.target_pos[0] - self.body_xyz[1], self.target_pos[0] - self.body_xyz[0]])` 

must be

` self.walk_target_dist_xyz = np.linalg.norm(
            [self.target_pos[2] - self.body_xyz[2], self.target_pos[1] - self.body_xyz[1], self.target_pos[0] - self.body_xyz[0]])` am I right? 

Thank you.

**Comment by fxia22** [comment]
Yes you are right, thanks for finding the issue. It is indeed a bug and it will affect the training of ant because only that agent is able to climb stairs.
