### ISSUE TITLE
Failed to build from source

### ISSUE THREAD

**Issue by chaundm** [StanfordVL/GibsonEnv#105]
Could you help me to fix this error?

In file included from /home/cndm/Documents/GibsonEnv/gibson/core/channels/common/controls.cpp:9:0:
/usr/include/glm/gtx/transform.hpp:23:3: error: #error "GLM: GLM_GTX_transform is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
 # error "GLM: GLM_GTX_transform is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
   ^~~~~
In file included from /usr/include/glm/gtx/quaternion.hpp:20:0,
                 from /home/cndm/Documents/GibsonEnv/gibson/core/channels/common/controls.cpp:11:
/usr/include/glm/gtx/norm.hpp:21:3: error: #error "GLM: GLM_GTX_norm is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
 # error "GLM: GLM_GTX_norm is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
   ^~~~~
In file included from /home/cndm/Documents/GibsonEnv/gibson/core/channels/common/controls.cpp:11:0:
/usr/include/glm/gtx/quaternion.hpp:23:3: error: #error "GLM: GLM_GTX_quaternion is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
 # error "GLM: GLM_GTX_quaternion is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
   ^~~~~
[ 84%] Building CXX object CMakeFiles/semantic.dir/external/lodepng/lodepng.cpp.o
In file included from /home/cndm/Documents/GibsonEnv/gibson/core/channels/depth_render/semantic.cpp:20:0:
/usr/include/glm/gtx/transform.hpp:23:3: error: #error "GLM: GLM_GTX_transform is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
 # error "GLM: GLM_GTX_transform is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
   ^~~~~
In file included from /usr/include/glm/gtx/quaternion.hpp:20:0,
                 from /home/cndm/Documents/GibsonEnv/gibson/core/channels/depth_render/semantic.cpp:22:
/usr/include/glm/gtx/norm.hpp:21:3: error: #error "GLM: GLM_GTX_norm is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
 # error "GLM: GLM_GTX_norm is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
   ^~~~~
In file included from /home/cndm/Documents/GibsonEnv/gibson/core/channels/depth_render/semantic.cpp:22:0:
/usr/include/glm/gtx/quaternion.hpp:23:3: error: #error "GLM: GLM_GTX_quaternion is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
 # error "GLM: GLM_GTX_quaternion is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
   ^~~~~
CMakeFiles/semantic.dir/build.make:134: recipe for target 'CMakeFiles/semantic.dir/common/controls.cpp.o' failed
make[2]: *** [CMakeFiles/semantic.dir/common/controls.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Scanning dependencies of target depth_render
CMakeFiles/semantic.dir/build.make:110: recipe for target 'CMakeFiles/semantic.dir/depth_render/semantic.cpp.o' failed
make[2]: *** [CMakeFiles/semantic.dir/depth_render/semantic.cpp.o] Error 1
[ 86%] Building C object CMakeFiles/depth_render.dir/glad/egl.c.o
[ 86%] Building C object CMakeFiles/depth_render.dir/glad/gl.c.o
[ 87%] Building CXX object CMakeFiles/depth_render.dir/common/shader.cpp.o
[ 88%] Building CXX object CMakeFiles/depth_render.dir/common/controls.cpp.o
[ 90%] Building CXX object CMakeFiles/depth_render.dir/common/texture.cpp.o
[ 90%] Building CXX object CMakeFiles/depth_render.dir/depth_render/render.cpp.o
[ 91%] Building CXX object CMakeFiles/depth_render.dir/common/MTLtexture.cpp.o
[ 92%] Building CXX object CMakeFiles/depth_render.dir/common/MTLplyloader.cpp.o
[ 93%] Building CXX object CMakeFiles/depth_render.dir/common/MTLobjloader.cpp.o
[ 94%] Building CXX object CMakeFiles/depth_render.dir/common/objloader.cpp.o
In file included from /home/cndm/Documents/GibsonEnv/gibson/core/channels/common/controls.cpp:9:0:
/usr/include/glm/gtx/transform.hpp:23:3: error: #error "GLM: GLM_GTX_transform is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
 # error "GLM: GLM_GTX_transform is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
   ^~~~~
In file included from /usr/include/glm/gtx/quaternion.hpp:20:0,
                 from /home/cndm/Documents/GibsonEnv/gibson/core/channels/common/controls.cpp:11:
/usr/include/glm/gtx/norm.hpp:21:3: error: #error "GLM: GLM_GTX_norm is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
 # error "GLM: GLM_GTX_norm is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
   ^~~~~
In file included from /home/cndm/Documents/GibsonEnv/gibson/core/channels/common/controls.cpp:11:0:
/usr/include/glm/gtx/quaternion.hpp:23:3: error: #error "GLM: GLM_GTX_quaternion is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
 # error "GLM: GLM_GTX_quaternion is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
   ^~~~~
[ 95%] Building CXX object CMakeFiles/depth_render.dir/common/tinyply.cpp.o
[ 96%] Building CXX object CMakeFiles/depth_render.dir/common/vboindexer.cpp.o
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/semantic.dir/all' failed
make[1]: *** [CMakeFiles/semantic.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 97%] Building CXX object CMakeFiles/depth_render.dir/common/text2D.cpp.o
[ 98%] Building CXX object CMakeFiles/depth_render.dir/external/lodepng/lodepng.cpp.o
In file included from /home/cndm/Documents/GibsonEnv/gibson/core/channels/depth_render/render.cpp:22:0:
/usr/include/glm/gtx/transform.hpp:23:3: error: #error "GLM: GLM_GTX_transform is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
 # error "GLM: GLM_GTX_transform is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
   ^~~~~
In file included from /usr/include/glm/gtx/quaternion.hpp:20:0,
                 from /home/cndm/Documents/GibsonEnv/gibson/core/channels/depth_render/render.cpp:24:
/usr/include/glm/gtx/norm.hpp:21:3: error: #error "GLM: GLM_GTX_norm is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
 # error "GLM: GLM_GTX_norm is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
   ^~~~~
In file included from /home/cndm/Documents/GibsonEnv/gibson/core/channels/depth_render/render.cpp:24:0:
/usr/include/glm/gtx/quaternion.hpp:23:3: error: #error "GLM: GLM_GTX_quaternion is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
 # error "GLM: GLM_GTX_quaternion is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
   ^~~~~
CMakeFiles/depth_render.dir/build.make:165: recipe for target 'CMakeFiles/depth_render.dir/common/controls.cpp.o' failed
make[2]: *** [CMakeFiles/depth_render.dir/common/controls.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/cndm/Documents/GibsonEnv/gibson/core/channels/depth_render/render.cpp: In function ‘int main(int, char**)’:
/home/cndm/Documents/GibsonEnv/gibson/core/channels/depth_render/render.cpp:698:33: warning: ‘cudaError_t cudaGLSetGLDevice(int)’ is deprecated [-Wdeprecated-declarations]
     cudaGLSetGLDevice(cudaDevice);
                                 ^
In file included from /home/cndm/Documents/GibsonEnv/gibson/core/channels/depth_render/render.cpp:28:0:
/usr/local/cuda-10.1/include/cuda_gl_interop.h:305:57: note: declared here
 extern __CUDA_DEPRECATED __host__ cudaError_t CUDARTAPI cudaGLSetGLDevice(int device);
                                                         ^~~~~~~~~~~~~~~~~
CMakeFiles/depth_render.dir/build.make:117: recipe for target 'CMakeFiles/depth_render.dir/depth_render/render.cpp.o' failed
make[2]: *** [CMakeFiles/depth_render.dir/depth_render/render.cpp.o] Error 1
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/depth_render.dir/all' failed
make[1]: *** [CMakeFiles/depth_render.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
/home/cndm/Documents/GibsonEnv
/home/cndm/Documents/GibsonEnv

**Comment by fxia22** [comment]
it is the same as #54
