### ISSUE TITLE
Cannot navigate the husky to render images: Unable to initialize EGL

### ISSUE THREAD

**Issue by chaundm** [StanfordVL/GibsonEnv#106]
Please help me to fix this issue when I run this command
python examples/demo/play_husky_camera.py
I cannot do anything in GUI environment except zooming the room. The RGB images show me black screen while the GUI environment does not respond

but this command for navigating husky works perfectly 
python examples/demo/play_husky_nonviz.py

And here is the screenshot for my problem

![Screenshot from 2019-12-17 11-41-15](https://user-images.githubusercontent.com/11848133/70963153-a740af80-20c2-11ea-8a42-ebda23b86fc2.png)

**Comment by fxia22** [comment]
can you show the full log? Thanks

**Comment by chaundm** [comment]
Thank you for your respond

Please find my following log file as screenshot. As you can see, it stopped at the line "Episode count: 0"

And here is the details of my pc:
Ubuntu: 18.04
CUDA 10.1
RTX2070 (eGPU): 8Gb
NVIDIA driver: 418

![Screenshot from 2019-12-19 12-05-45](https://user-images.githubusercontent.com/11848133/71144198-2a473e80-2258-11ea-9b65-5dd88624942a.png)

**Comment by fxia22** [comment]
Got it, can you try the methods here and see if it gets resolved? http://svl.stanford.edu/gibson2/docs/issues.html

**Comment by chaundm** [comment]
Thanks a lot, I solved it by stopping X server 

![Screenshot from 2019-12-20 17-27-40](https://user-images.githubusercontent.com/11848133/71244689-0fef8c80-234e-11ea-97b0-a3768db977dd.png)
