### ISSUE TITLE
Super slow simulation after adding "rgb_filled' in output (Frame rate: 12) GPU: NVIDIA 1080 GTX

### ISSUE THREAD

**Issue by zubair-irshad** [StanfordVL/GibsonEnv#107]
Simulations gets super slow after I add "rgb_filled" to my output within the config file. Any leads would be appreciated!

**Comment by zubair-irshad** [comment]
![Screenshot from 2019-12-23 15-00-57](https://user-images.githubusercontent.com/32943733/71378237-20de0f00-2595-11ea-9d74-c0a5479e040c.png)

**Comment by Berk035** [comment]
Hello @zubair-irshad,

RGB_FILLED may cause that lots of data calculation in simulation as DEPTH mode uses less. Another option for problem is sensitive timestep and frame_skip values. I suggest to you increasing frame_skip values in config file. Have a nice day.

**Comment by zubair-irshad** [comment]
Awesome. Thabks @Berk035 
May I ask what timestep and frame_skip values worked for you? Also what fps did you get after optimization?
