### ISSUE TITLE
camera intrinsic parameter

### ISSUE THREAD

**Issue by gao-navigation** [StanfordVL/GibsonEnv#117]
Hi, Are there any ways to get the intrinsic parameter of this simulation camera in the Gibson?

**Comment by Berk035** [comment]
Hi @gao-navigation ,

What kind of parameters do you want, could you explain more?

**Comment by gao-navigation** [comment]
Thanks for your response.  Intrinsic parameter of the camera is the matrix with 3 rows and 3 columns. As for the real camera, we can get it through camera calibration. For the Intrinsic parameter of this simulation camera, can we calculate it directly ?
