### ISSUE TITLE
Geodesic Distance on V1

### ISSUE THREAD

**Issue by Berk035** [StanfordVL/GibsonEnv#119]
Hello dear contibuters, 

I know that you are studying with iGibson and GibsonV2 nowadays; but I wonder it, can I measure the geodesic distance and shortest path on GibsonV1? Thank you.

**Comment by fxia22** [comment]
Hi @Berk035, I believe you can use the same code snipped as used in iGibson to calculate geodesic distance:

https://github.com/StanfordVL/iGibson/blob/master/gibson2/core/physics/scene.py#L335-L365

**Comment by Berk035** [comment]
Thanks for your response @fxia22,
I tried to use it, but I need to build graph for finding path.
