### ISSUE TITLE
Scenes previews aren't available anymore on the Gibson website

### ISSUE THREAD

**Issue by mathfac** [StanfordVL/GibsonEnv#123]
Scenes previews aren't available anymore on the Gibson website:
https://gibsonenv.github.io/database/
That was useful reference for debugging issues to take a look on the particular scenes. Thank you!

**Comment by amir32002** [comment]
You can use the main website:

http://gibsonenv.stanford.edu/ 
http://gibsonenv.stanford.edu/database/

**Comment by mathfac** [comment]
Thank you, @amir32002!
