### ISSUE TITLE
Can not download dataset from storage.googleapis

### ISSUE THREAD

**Issue by seungju-mmc** [StanfordVL/GibsonEnv#127]
I run a command in ubuntu terminal
wget https://storage.googleapis.com/gibsonassets/dataset.tar.gz
instead of download, I got the forbidden message

Also, i access the path by chrome.
![Screenshot from 2021-05-06 16-21-33](https://user-images.githubusercontent.com/61035345/117257703-2769df80-ae87-11eb-8415-5eb472091c3f.png)

**Comment by leokonto** [comment]
I am having the same problem and get `Error: 403` when executing `/.downloads.sh`

**Comment by fxia22** [comment]
Just fixed it, feel free to try again.

**Comment by kohjingyu** [comment]
I'm experiencing this issue again, as of today.

**Comment by fxia22** [comment]
@kohjingyu I just tried and things seem to be fine, can you file in the gibson dataset agreement again to get the new links?

**Comment by kohjingyu** [comment]
@fxia22 Thanks for the quick response - the new links work!
