### ISSUE TITLE
GibsonEnv Website is down?

### ISSUE THREAD

**Issue by ugurbolat** [StanfordVL/GibsonEnv#128]
Cannot access the agreement pdf website link for signing the license agreement to download the dataset.

http://svl.stanford.edu/gibson2/assets/GDS_agreement.pdf

Also, http://gibsonenv.stanford.edu/ seems to be not accessible as well.

**Comment by fxia22** [comment]
I can still access it, can you try again?

**Comment by ugurbolat** [comment]
Now I can access it too.

Thanks for the reply.
