### ISSUE TITLE
Can not download assets_core_v2.tar.gz from storage.googleapis

### ISSUE THREAD

**Issue by zshzdt** [StanfordVL/GibsonEnv#131]
I ran command "./download.sh", but it gave the word "HTTP request sent, awaiting response... 404 Not Found" when downloading assets_core_v2.tar.gz, but it works when I download dataset.tar.gz, so I am really puzzled about this. Is assets_core_v2.tar.gz not exists.

**Comment by fxia22** [comment]
You can try again, I think it should work now.

**Comment by zshzdt** [comment]
It works fine, thank you very much!
