### ISSUE TITLE
Depth render fail large models

### ISSUE THREAD

**Issue by hzyjerry** [StanfordVL/GibsonEnv#15]
Error message:

> depth_render: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

Potentially due to memory overflow

**Comment by fxia22** [comment]
solve by [this commit](https://github.com/StanfordVL/GibsonEnv/commit/73ce9a44c7a1443ff72fbeba13035116fa8c4fda).
