### ISSUE TITLE
Some Questions About GibsonEnv

### ISSUE THREAD

**Issue by katiekang1998** [StanfordVL/GibsonEnv#17]
- where in the code can we access the u function for the real world image goggles?
- is the camera field of view parameter in the yaml referring to the diagonal of the image or the side?
- when setting the position of a robot, what is the unit of the position?

Thanks!

**Comment by fxia22** [comment]
2, the field of view in yaml file corresponds to vertical and horizontal field of view, not diagonal.
3, The unit is in meters.

As for 1, we haven't delivered the trained u function yet, we will release that very soon.

**Comment by katiekang1998** [comment]
thanks!
