### ISSUE TITLE
How to scan real scenes

### ISSUE THREAD

**Issue by denghan6688** [StanfordVL/GibsonEnv#20]
How can I scan the 3D model of the environment?

**Comment by amir32002** [comment]
Below is a brief answer, but please note that **in Gibson our goal is turning some already scanned and processed places into a virtual perceptual environment. Our focus is not providing a streamlined tool for scanning new buildings, as that's a sufficiently separate problem**. We recommend using the hundreds of spaces already included in Gibson database, as its scale should (hopefully) be sufficient for developing agents that generalize to novel spaces.

However, Gibson's format of the asset data of a space (i.e. each folder in `gibson/assets/dataset/`) is straightforward. As long as you scan a new space and store it following the same format, Gibson will be able to open it. Some of the requirements are listed below. You can scan the space using one of the existing scanning devices, e.g. Paracosm, DotProduct, Matterport, etc. Gibson is agnostic to scanning hardware.  

1. you need to store the RGB images of the space as equirectangular panoramas in `panos/rgb` folder. Note the resolution and aspect ratio. 
2. For each RGB panorama, you need a corresponding depth panorama saved in `pano/mist` folder.
3. you need a mesh containing the 3D geometry of the space in obj format saved as `mesh.obj` and a 90 degree rotated version of it saved as `mesh_z_up.obj`. The first one is used for image rendering and the second in physics engine. 
4. you need to save the camera pose information for each image in `camera_poses.csv` and in individual files in `panos/points` folder. 
5. you need to preserve the naming convention of the existing asset folders.

**Comment by denghan6688** [comment]
First of all, thank you very much for your answer. I want to know if I still need to retrain the network after scanning the scene myself and if you are open source.

**Comment by songWell** [comment]
Hi, thank you for your answer. I want to know if there is a depth factor for the corresponding depth panorama ?
https://github.com/StanfordVL/GibsonEnv/issues/139
