### ISSUE TITLE
Spotty Camera Images

### ISSUE THREAD

**Issue by katiekang1998** [StanfordVL/GibsonEnv#22]
I am running play_drone_camera.py through Allensville, with orientation [0, 0, 1.75] and position [2.6, 2, 0.4], and this is the output I get with rgb_prefilled, rgb_filled, and depth. It seems like there's a lot of missing spots in rbg_prefilled. Am I running something incorrectly, or are there certain viewpoints in the models where there are a lot of holes?

![screenshot from 2018-07-26 12-07-48](https://user-images.githubusercontent.com/16585531/43283356-86a74058-90cd-11e8-9b9f-6be286f0a447.png)

**Comment by fxia22** [comment]
It looks like depth_render opened a wrong model, that might come from the last session where the process didn't terminate properly. You can run `ps -ef | grep depth_render` to find that process and kill with `pkill depth_render` then start Gibson again. 

I tested the coordinate you sent and that works for me.

![image](https://user-images.githubusercontent.com/5158896/43436536-ad5605b2-9439-11e8-9b0a-c6f7aab04849.png)
