### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: ../coord.npy

### ISSUE THREAD

**Issue by JobSmith** [StanfordVL/GibsonEnv#27]
When I execute this command:
```
python examples/demo/play_husky_nonviz.py
```
It shows me this error:
```
Traceback (most recent call last):
  File "play_husky_nonviz.py", line 1, in <module>
    from gibson.envs.husky_env import HuskyNavigateEnv
  File "/home/amax/Python/GibsonEnv/gibson/envs/husky_env.py", line 1, in <module>
    from gibson.envs.env_modalities import CameraRobotEnv, BaseRobotEnv, SemanticRobotEnv
  File "/home/amax/Python/GibsonEnv/gibson/envs/env_modalities.py", line 2, in <module>
    from gibson.core.render.pcrender import PCRenderer
  File "/home/amax/Python/GibsonEnv/gibson/core/render/pcrender.py", line 32, in <module>
    coords  = np.load(os.path.join(assets_file_dir, 'coord.npy'))
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/amax/Python/GibsonEnv/gibson/assets/coord.npy'
```

**Comment by fxia22** [comment]
Hi @JobSmith, have you downloaded the assets file from https://storage.googleapis.com/gibsonassets/assets_core_v2.tar.gz and decompress it to `/home/amax/Python/GibsonEnv/gibson/assets` folder?

**Comment by JobSmith** [comment]
Yeah! As you can see, I downloaded the file and put it in the catalog: /home/amax/Python/GibsonEnv/gibson/ .
![image](https://user-images.githubusercontent.com/15700681/44436513-34b3e280-a5e8-11e8-902b-434a4185598b.png)

**Comment by fxia22** [comment]
Can you show `ls /home/amax/Python/GibsonEnv/gibson/assets/`? You should be able to find `coord.npy` in that folder.

**Comment by JobSmith** [comment]
![image](https://user-images.githubusercontent.com/15700681/44437210-93c72680-a5eb-11e8-9a2b-c5afd44e5d65.png)

**Comment by JobSmith** [comment]
I see! The file I downloaded a month ago.
Maybe you have updated it.
