### ISSUE TITLE
Downloading only semantics dataset

### ISSUE THREAD

**Issue by jackaceuser** [StanfordVL/GibsonEnv#38]
If I'm interested only in the semantic segmented parts of the dataset.

Which dataset should I download?
Where is the format specification? (I guess it's just a PNG with color encoding according to what is specified in semantic_color.hpp?)

**Comment by amir32002** [comment]
As of now semantic channel is supported for Stanford 2D-3D-Semantics dataset and Matterport3D (see [here](https://github.com/StanfordVL/GibsonEnv/blob/master/gibson/data/README.md#download-gibson-database-of-spaces) for how to access them). We'll release semantics for the rest of the data later. 

Please see [here](https://github.com/StanfordVL/GibsonEnv#rendering-semantics) and [here](https://github.com/StanfordVL/GibsonEnv/blob/master/gibson/utils/semantics.md#instruction-for-using-gibson-with-semantics) for instructions on using the semantic channel.

**Comment by jackaceuser** [comment]
Thanks.
I now can see the semantic.obj file in the 2d3ds_for_gibson\<area>\semantic.obj folders.
Could you please refer me to its' format description?

**Comment by amir32002** [comment]
This [repo](https://github.com/alexsax/2D-3D-Semantics) should clarify. Please scroll down to 3D Modalities" and "3D Semantic Mesh".

**Comment by kowshikthopalli** [comment]
> As of now semantic channel is supported for Stanford 2D-3D-Semantics dataset and Matterport3D (see [here](https://github.com/StanfordVL/GibsonEnv/blob/master/gibson/data/README.md#download-gibson-database-of-spaces) for how to access them in Gibson). We'll release semantics for the rest of the data later.
> 
> Please see [here](https://github.com/StanfordVL/GibsonEnv#rendering-semantics) and [here](https://github.com/StanfordVL/GibsonEnv/blob/master/gibson/utils/semantics.md#instruction-for-using-gibson-with-semantics) for instructions on using the semantic channel.

Hi  Thanks for the great work. I was wondering what is the status of releasing the semantic segmentations of Gibson dataset.

**Comment by amir32002** [comment]
@kowshikthopalli we have a paper on that under review. We're planning on releasing the data once we get the acceptance notification.
