### ISSUE TITLE
Gibson on remote server hangs when loading

### ISSUE THREAD

**Issue by glewis17** [StanfordVL/GibsonEnv#43]
When running on Deep Learning AMI (Ubuntu) Version 12.0 on a p2.xlarge AWS machine, gibson hangs at line 128:`self.socket_mist.connect("tcp://localhost:{}").format(self.port-1)` in file `gibson/core/render/pcrender.py`. Any tips on what may be wrong?

**Comment by fxia22** [comment]
For AWS, the one possible setup is to use this [AMI](https://aws.amazon.com/marketplace/pp/B076K31M1S) and use the NGC image [here](https://github.com/StanfordVL/GibsonEnv/wiki#how-can-i-run-gibson-on-ngc)

**Comment by fxia22** [comment]
Hi Gene, please see the updated set up guide in the readme. It should be the same as the steps I walked you through last week in my office. Let me know how it goes.

**Comment by glewis17** [comment]
Confirmed working on a new machine, thanks!
