### ISSUE TITLE
About gibson.utils.pposgd_fuse.py

### ISSUE THREAD

**Issue by stbook** [StanfordVL/GibsonEnv#55]
At line 88 of gibson.utils.pposgd_fuse.py, I think it should be
`yield {"ob": obs, "ob_sensor": obs_sensor, "rew": rews, "vpred": vpreds, "new": news,`

**Comment by fxia22** [comment]
Yes you are right, thanks for catching this. We will fix this.

**Comment by stbook** [comment]
Would you mind sharing some trained flagRun models on non-test scenes?
The training just take too much time to converge.
