### ISSUE TITLE
Show diagnostics during training

### ISSUE THREAD

**Issue by DrSleep** [StanfordVL/GibsonEnv#59]
Hello, 

I have a small question with regards to the training config file - in particular, this line: https://github.com/StanfordVL/GibsonEnv/blob/master/examples/configs/husky_navigate_rgb_train.yaml#L12

Is `show_diagnostics` supposed to be `True`? If I understand correctly, this would mess up with the rgb input to the agent, which then questions usefulness of the rgb input at all

Thanks, and great work, btw!

**Comment by fxia22** [comment]
Hi @DrSleep, you are right, `show_diagnostics` should be `false` in any training and testing configurations. We will push a fix.

**Comment by DrSleep** [comment]
@fxia22 thanks!
