### ISSUE TITLE
How can I import other  agents in GibsonEnv?

### ISSUE THREAD

**Issue by marooncn** [StanfordVL/GibsonEnv#66]
Hi, I want to use [MiR100 Robot](https://github.com/dfki-ric/mir_robot) in GibsonEnv. How can I come it true?

**Comment by fxia22** [comment]
Hi @marooncn, it should not be too difficult to import this robot to Gibson as the urdf files are already available. You can copy [this part of code](https://github.com/StanfordVL/GibsonEnv/blob/master/gibson/core/physics/robot_locomotors.py#L758-L824) to create your own robot. You will need some changes including the following:

- add a link to the urdf named "eyes", that's what we use as a reference frame to render images
- set control for each motor: for example `control=['velocity', 'velocity', 'position', 'position']` means that we have 4 motors and use velocity control for first two motors and position control for the rest.
- implement an action list if you want discretized actions.
