### ISSUE TITLE
Inconsistency in number of models 

### ISSUE THREAD

**Issue by anoopsonar30** [StanfordVL/GibsonEnv#68]
I've been trying to use the navigation metrics to support initializing in multiple environments.

How many models of building spaces does gibson_full have? It seems to have only 360 however there are 500 json files in the navigation metrics for gibson_full. It seems the other 140 are not in the gibson_full tar file.

**Comment by fxia22** [comment]
Hi @anoopsonar30 , the gibson dataset is built in an incremental manner. You need to get tiny + medium + full + fullplus to get all 572 models.
