### ISSUE TITLE
Detecting collisions

### ISSUE THREAD

**Issue by anoopsonar30** [StanfordVL/GibsonEnv#69]
I'm using Gibson to run quadrotor simulations. I wanted to know how I could detect collisions between the agent and the environment. So far I've been using approximate methods to do that but they're not completely accurate. Is there an accurate way of doing it maybe by using the underlying pybullet engine or do you already have a higher level function which I can simply call?

**Comment by fxia22** [comment]
Hi @anoopsonar30 thanks for your interest, we don't have a higher level function for detecting collisions in Gibson Env. But you should be able to implement one using pybullet. You can read more in Collision Detection Queries section in [pybullet guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#).

You can use `getContactPoints` function to query collision between two bodies. It takes in two bodies ids,. ids of robot can be found in `env.robot.robot_ids` and ids of the environment(building) can be found in `env.ground_ids`
