### ISSUE TITLE
Change the camera height, do not affect physics

### ISSUE THREAD

**Issue by bradleyemi** [StanfordVL/GibsonEnv#73]
Hi, is it possible to change the camera height of the robot without changing the underlying physics of the robot? Could you please point me in the right direction on which file to change?

Thanks!

**Comment by fxia22** [comment]
Hi @bradleyemi , you can edit the "eye_joint" to make it higher or lower. The eye_link doesn't have mass so it should not affect the physics. However, keep in mind that making the eyes higher will make the vibrations of the robot more visible as the eyes don't come with a stabilizing mechanism.
