### ISSUE TITLE
Camera Intrinsic Matrix

### ISSUE THREAD

**Issue by stbook** [StanfordVL/GibsonEnv#77]
I know that GibsonEnv use NN to do the rendering. But is there a way to get to know the intrinsic matrix of the camera? Because I think the input parameter 'fov' doesn't affect the output RGB image here.

**Comment by placeforyiming** [comment]
> I know that GibsonEnv use NN to do the rendering. But is there a way to get to know the intrinsic matrix of the camera? Because I think the input parameter 'fov' doesn't affect the output RGB image here.

Hi,

Did you get that?

**Comment by fxia22** [comment]
@placeforyiming It is a pin-hole camera model with a certain fov. So there is no skew, optical center is the image center and focal length can be calculated from field of view.

**Comment by NaveenSehgal** [comment]
> @placeforyiming It is a pin-hole camera model with a certain fov. So there is no skew, optical center is the image center and focal length can be calculated from field of view.

How exactly is the focal length calculated from field of view? Don't you need sensor size to do this?

**Comment by stbook** [comment]
> > I know that GibsonEnv use NN to do the rendering. But is there a way to get to know the intrinsic matrix of the camera? Because I think the input parameter 'fov' doesn't affect the output RGB image here.
> 
> Hi,
> 
> Did you get that?

If the resolution of the observation is (256, 256), then the focal length is 128.
