### ISSUE TITLE
Cannot find val and test dataset

### ISSUE THREAD

**Issue by tonytonglt** [StanfordVL/GibsonEnv#97]
Hi, I have downloaded the gibson_full partition dataset and there were 360 models in it. Referring to your Dataset Splits, it should be 360 train and other 70 val and 70 test, but I cannot find val and test dataset. Could you tell me where I can find and download them? Thx.

**Comment by fxia22** [comment]
The dataset is built in an incremental manner, you need to download all the partitions including tiny and medium.

**Comment by tonytonglt** [comment]
> The dataset is built in an incremental manner, you need to download all the partitions including tiny and medium.

Got it! Thank you very much.
