### ISSUE TITLE
Difference with gibson dataset for habitat-sim

### ISSUE THREAD

**Issue by StOnEGiggity** [StanfordVL/GibsonEnv#98]
Hi, I download gibson dataset for habitat-sim in July, which is about 1.5g. Now I find it is 10g. Is there any doc about the difference or update information

**Comment by fxia22** [comment]
I believe it is a different split. The 1.5G is for habitat challenge at CVPR and the full data is 10G.

**Comment by liucsg** [comment]
Hi，could you tell me which is mail  address of gibson dataset to request? @StOnEGiggity
